name: Push Image To GCP

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    env:
      REGISTRY_PATH: "${{ secrets.REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}"
      APP_IMAGE: pal


    permissions: 
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - id: gcloud-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WI_PROVIDER_ID }}'
          service_account: '${{ secrets.GSA_ID }}'
          access_token_lifetime: 3600s
          # legacy way
          # credentials_json: ${{ secrets.GCP_SA_JSON }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Sign Into Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.REGISTRY_LOCATION }}-docker.pkg.dev --quiet

      - name: Build + Push Pal Image
        run: |
          docker build -t  ${{ env.REGISTRY_PATH }}/${{ env.APP_IMAGE }}:latest ./pal
          docker push  ${{ env.REGISTRY_PATH }}/${{ env.APP_IMAGE }}:latest

